apiVersion: v1
kind: Service
metadata:
  labels:
    app: authors
  name: authors-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 9080
  selector:
    app: authors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-deployment
  labels:
    app: authors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors
  template:
    metadata:
      labels:
        app: authors
    spec:
      containers:
      - name: authors
        image: APPLICATION_IMAGE
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: authors
  name: authors-route
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: authors-service